"""
Shared constant values used across the project.
"""

APP_TITLE = "Spot the Difference Game"

SUPPORTED_IMAGE_FORMATS = (".jpg", ".jpeg", ".png", ".bmp")

MIN_IMAGE_WIDTH = 250
MIN_IMAGE_HEIGHT = 180

NUMBER_OF_DIFFERENCES = 5
MAX_MISTAKES = 3
CLICK_TOLERANCE = 14

MAX_DISPLAY_WIDTH = 1000
MAX_DISPLAY_HEIGHT = 750
MIN_DISPLAY_WIDTH = 380
MIN_DISPLAY_HEIGHT = 280

FOUND_COLOUR = (0, 0, 255)
REVEAL_COLOUR = (255, 0, 0)

APP_FONT_FAMILY = "Helvetica Neue"

APP_FONT_TITLE = (APP_FONT_FAMILY, 20, "bold")
APP_FONT_SUBTITLE = (APP_FONT_FAMILY, 11)
APP_FONT_NORMAL = (APP_FONT_FAMILY, 11)
APP_FONT_BOLD = (APP_FONT_FAMILY, 11, "bold")
APP_FONT_BUTTON = (APP_FONT_FAMILY, 11, "bold")
APP_FONT_STATUS = (APP_FONT_FAMILY, 12)
APP_FONT_CARD_TITLE = (APP_FONT_FAMILY, 12, "bold")

APP_BACKGROUND_COLOUR = "#F3F4F6"
CARD_BACKGROUND_COLOUR = "#FFFFFF"
TEXT_COLOUR = "#111827"
MUTED_TEXT_COLOUR = "#6B7280"
BORDER_COLOUR = "#D1D5DB"

STATUS_BACKGROUND_COLOUR = "#374151"
STATUS_TEXT_COLOUR = "#F9FAFB"
STATUS_ACCENT_COLOUR = "#6B7280"

IMAGE_PLACEHOLDER_BACKGROUND = "#E5E7EB"

BUTTON_TEXT_COLOUR = "#FFFFFF"
PRIMARY_COLOUR = "#2563EB"
PRIMARY_HOVER_COLOUR = "#1D4ED8"
SECONDARY_COLOUR = "#4B5563"
SECONDARY_HOVER_COLOUR = "#374151"

BUTTON_PADDING_X = 16
BUTTON_PADDING_Y = 7
BUTTON_RIGHT_MARGIN = 8

IMAGE_AREA_MIN_WIDTH = 420
IMAGE_AREA_MIN_HEIGHT = 300

PLACEHOLDER_WRAP_LENGTH = 340
PLACEHOLDER_PADDING_X = 18
PLACEHOLDER_PADDING_Y = 18

WINDOW_MIN_WIDTH = 1050
WINDOW_MIN_HEIGHT = 650

SCREEN_WIDTH_RESERVED_SPACE = 80
SCREEN_HEIGHT_RESERVED_SPACE = 220

IMAGE_DISPLAY_INNER_PADDING = 12
MIN_AVAILABLE_IMAGE_DISPLAY_SIZE = 120
MIN_VALID_WIDGET_SIZE = 1

DEFAULT_DISPLAY_SCALE = 1.0

IMAGE_LABEL_PADDING = 0
IMAGE_LABEL_BORDER_WIDTH = 0
IMAGE_LABEL_HIGHLIGHT_THICKNESS = 0

MAIN_CONTAINER_PADDING_X = 18
MAIN_CONTAINER_PADDING_Y = 16

HEADER_BOTTOM_MARGIN = 14
HEADER_SUBTITLE_TOP_MARGIN = 3

CONTROL_PANEL_PADDING_X = 14
CONTROL_PANEL_PADDING_Y = 12
CONTROL_PANEL_BOTTOM_MARGIN = 12

BORDER_THICKNESS = 1

STAT_CARD_LEFT_MARGIN = 8
STAT_CARD_PADDING_X = 12
STAT_CARD_PADDING_Y = 6

STATUS_BAR_BOTTOM_MARGIN = 12
STATUS_ACCENT_BAR_WIDTH = 5
STATUS_LABEL_PADDING_X = 12
STATUS_LABEL_PADDING_Y = 9
STATUS_LABEL_WRAP_LENGTH = 900

IMAGE_CARD_PADDING_X = 12
IMAGE_CARD_PADDING_Y = 12
IMAGE_CARD_SIDE_MARGIN = 8
IMAGE_CARD_TITLE_BOTTOM_MARGIN = 8

ZERO_SPACING = 0
ZERO_BORDER = 0

MIN_DIFFERENCE_AREA_SIZE_DIVISOR = 25
MAX_DIFFERENCE_AREA_SIZE_DIVISOR = 5

BLUR_KERNEL_SIZE = 21
BRIGHTNESS_CHANGE_BETA = 45

MIN_REGION_DETAIL_SCORE = 8
MAX_REGION_CREATION_ATTEMPTS = 300

PIXELATE_SCALE_DOWN_FACTOR = 8
HUE_SHIFT_VALUE = 20
SATURATION_SHIFT_VALUE = 35

BLUR_EDGE_THRESHOLD_LOW = 50
BLUR_EDGE_THRESHOLD_HIGH = 150
MIN_BLUR_EDGE_DENSITY = 0.015

PLAIN_REGION_BRIGHTNESS_THRESHOLD = 170
PLAIN_REGION_BLUR_BRIGHTNESS_CHANGE = 25

CONTRAST_EFFECT_ALPHA = 1.35
CONTRAST_EFFECT_BETA = 0