"""
Shared constant values used across the project.
"""

APP_TITLE = "Spot the Difference Game"

SUPPORTED_IMAGE_FORMATS = (".jpg", ".jpeg", ".png", ".bmp")

MIN_IMAGE_WIDTH = 250
MIN_IMAGE_HEIGHT = 180

NUMBER_OF_DIFFERENCES = 5
MAX_MISTAKES = 3
CLICK_TOLERANCE = 14

MAX_DISPLAY_WIDTH = 650
MAX_DISPLAY_HEIGHT = 520

MIN_DISPLAY_WIDTH = 340
MIN_DISPLAY_HEIGHT = 250

WINDOW_MIN_WIDTH = 1350
WINDOW_MIN_HEIGHT = 780

FOUND_COLOUR = (0, 0, 255)
REVEAL_COLOUR = (255, 0, 0)

APP_FONT_FAMILY = "Helvetica Neue"

APP_FONT_TITLE = (APP_FONT_FAMILY, 20, "bold")
APP_FONT_SUBTITLE = (APP_FONT_FAMILY, 11)
APP_FONT_NORMAL = (APP_FONT_FAMILY, 11)
APP_FONT_BOLD = (APP_FONT_FAMILY, 11, "bold")
APP_FONT_BUTTON = (APP_FONT_FAMILY, 11, "bold")
APP_FONT_STATUS = (APP_FONT_FAMILY, 12)
APP_FONT_CARD_TITLE = (APP_FONT_FAMILY, 12, "bold")

APP_BACKGROUND_COLOUR = "#F3F4F6"
CARD_BACKGROUND_COLOUR = "#FFFFFF"
TEXT_COLOUR = "#111827"
MUTED_TEXT_COLOUR = "#6B7280"
BORDER_COLOUR = "#D1D5DB"

STATUS_BACKGROUND_COLOUR = "#374151"
STATUS_TEXT_COLOUR = "#F9FAFB"
STATUS_ACCENT_COLOUR = "#6B7280"

IMAGE_PLACEHOLDER_BACKGROUND = "#E5E7EB"

BUTTON_TEXT_COLOUR = "#FFFFFF"
PRIMARY_COLOUR = "#2563EB"
PRIMARY_HOVER_COLOUR = "#1D4ED8"
SECONDARY_COLOUR = "#4B5563"
SECONDARY_HOVER_COLOUR = "#374151"

BUTTON_PADDING_X = 16
BUTTON_PADDING_Y = 7
BUTTON_RIGHT_MARGIN = 8

IMAGE_AREA_MIN_WIDTH = 420
IMAGE_AREA_MIN_HEIGHT = 300

PLACEHOLDER_WRAP_LENGTH = 340
PLACEHOLDER_PADDING_X = 18
PLACEHOLDER_PADDING_Y = 18

SCREEN_WIDTH_RESERVED_SPACE = 80
SCREEN_HEIGHT_RESERVED_SPACE = 220

IMAGE_DISPLAY_INNER_PADDING = 12
MIN_AVAILABLE_IMAGE_DISPLAY_SIZE = 120
MIN_VALID_WIDGET_SIZE = 1

DEFAULT_DISPLAY_SCALE = 1.0

IMAGE_LABEL_PADDING = 0
IMAGE_LABEL_BORDER_WIDTH = 0
IMAGE_LABEL_HIGHLIGHT_THICKNESS = 0

MAIN_CONTAINER_PADDING_X = 18
MAIN_CONTAINER_PADDING_Y = 16

HEADER_BOTTOM_MARGIN = 14
HEADER_SUBTITLE_TOP_MARGIN = 3

CONTROL_PANEL_PADDING_X = 14
CONTROL_PANEL_PADDING_Y = 12
CONTROL_PANEL_BOTTOM_MARGIN = 12

BORDER_THICKNESS = 1

STAT_CARD_LEFT_MARGIN = 8
STAT_CARD_PADDING_X = 12
STAT_CARD_PADDING_Y = 6

STATUS_BAR_BOTTOM_MARGIN = 12
STATUS_ACCENT_BAR_WIDTH = 5
STATUS_LABEL_PADDING_X = 12
STATUS_LABEL_PADDING_Y = 9
STATUS_LABEL_WRAP_LENGTH = 900

IMAGE_CARD_PADDING_X = 12
IMAGE_CARD_PADDING_Y = 12
IMAGE_CARD_SIDE_MARGIN = 8
IMAGE_CARD_TITLE_BOTTOM_MARGIN = 8

ZERO_SPACING = 0
ZERO_BORDER = 0

DIFFERENCE_CIRCLE_EXTRA_RADIUS = 10
DIFFERENCE_CIRCLE_MIN_GAP = 20

CANDIDATE_GRID_COLUMNS = 6
CANDIDATE_GRID_ROWS = 5
CANDIDATE_AREA_MIN_SCALE = 0.5
CANDIDATE_AREA_MAX_SCALE = 0.75

BLUR_EDGE_THRESHOLD_LOW = 50
BLUR_EDGE_THRESHOLD_HIGH = 150

#Color Shift Effect
COLOUR_HUE_SHIFT_VALUE = 12
COLOUR_SATURATION_SHIFT_VALUE = 18
COLOUR_EFFECT_BLEND_WEIGHT = 0.65

# Blur Effect
MIN_BLUR_EDGE_DENSITY = 0.05
BLUR_KERNEL_SIZE = 35

# Brightness Effect
BRIGHTNESS_CHANGE_BETA = 55
BRIGHTNESS_EFFECT_BLEND_WEIGHT = 0.65

# Greyscale Effect
GREYSCALE_EFFECT_BLEND_WEIGHT = 0.65

# Pixelate Effect
PIXELATE_SCALE_DOWN_FACTOR = 16
PIXELATE_VISIBILITY_ALPHA = 1.09
PIXELATE_VISIBILITY_BETA = 2

# Contrast Effect
CONTRAST_EFFECT_ALPHA = 1.45
CONTRAST_EFFECT_BETA = 0

# Plain / White Area Visibility Fix
PLAIN_AREA_BRIGHTNESS_THRESHOLD = 220
PLAIN_AREA_VISIBILITY_CHANGE = 40
PLAIN_AREA_VISIBILITY_BLEND_WEIGHT = 0.55

MIN_REGION_DETAIL_SCORE = 12
MIN_GREYSCALE_SATURATION = 25